version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8.5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install requests pyral
      - run:
          name: Run Python script
          command: |
            python app.py
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          cron: "*/2 * * * *"
