version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install requests pyral
      - run:
          name: Run the code
          command: |
            python app.py
    # Schedule the job to run every 2 minutes
    schedule:
      cron: "*/2 * * * *"
