You're trying to mount both ConfigMap resources into the /etc/blackbox_exporter/service_discovery directory using two separate volume mounts. However, both of them are mounted to the same directory path which could be problematic. If you mount multiple volumes to the exact same path in the container, the second one will overwrite the first one 


 
Mount the entire ConfigMap as directories instead of using subPath for individual files. This way, each file from a ConfigMap gets its own directory under /etc/blackbox_exporter/service_discovery.      



volumeMounts:
- name: service-discovery-east-a
  mountPath: /etc/blackbox_exporter/service_discovery/prom_file_sd_east-a
- name: service-discovery-east-b
  mountPath: /etc/blackbox_exporter/service_discovery/prom_file_sd_east-b

volumes:
- name: service-discovery-east-a
  configMap:
    name: prom-file-sd-east-config-a
- name: service-discovery-east-b
  configMap:
    name: prom-file-sd-east-config-b
The file prom_file_sd_east-a.json from the prom-file-sd-east-config-a ConfigMap will be available at /etc/blackbox_exporter/service_discovery/prom_file_sd_east-a/prom_file_sd_east-a.json in the container.

The file prom_file_sd_east-b.json from the prom-file-sd-east-config-b ConfigMap will be available at /etc/blackbox_exporter/service_discovery/prom_file_sd_east-b/prom_file_sd_east-b.json in the container.

Another minor point: there's a small syntax error in your volume definitions. It should be - name: ... (with a space after the dash) instead of -name: ....
      
      
      
      
  
 
